### ISSUE TITLE
Reading out the description

### ISSUE THREAD

**Issue by kings33** [alexa/skill-sample-nodejs-decision-tree#18]
After it selects an answer from the decision tree, if the person says Yes, they want to hear the short description, it just starts over...

```
// user has heard the final choice and has been asked if they want to hear the description or to play again
const descriptionHandlers = Alexa.CreateStateHandler(states.DESCRIPTIONMODE, {

 'AMAZON.YesIntent': function () {
        // Handle Yes intent.
        // reset the game state to start mode
        this.handler.state = states.STARTMODE;
        this.response.speak(welcomeMessage).listen(repeatWelcomeMessage);
        this.emit(':responseReady');
    },
```

Shouldn't this speak the description, and not go straight to Start Over?

**Comment by mcade** [comment]
The message at the end says, "Say 'tell me more' to hear a short description for this profession, or do you want to play again?" So saying yes means you want to start the game over. In order to hear a description you need to use one of the sample utterances for DescriptionIntent in your interaction model.

**Comment by akersh-s** [comment]
Clarifying this in PR #24

**Comment by franklin-lobb** [comment]
@kings33 @mcade Is this still occurring in the new version of the skill?
