### ISSUE TITLE
Script error in index.js

### ISSUE THREAD

**Issue by blacktiger333** [alexa/skill-sample-nodejs-decision-tree#31]
If I run the sample I got a script error (copy and pasted original code) => CloudWatch Log:
Syntax error in module 'index': SyntaxError
)
^
SyntaxError: Unexpected token )
at createScript (vm.js:56:10)
at Object.runInThisContext (vm.js:97:10)
at Module._compile (module.js:542:28)
at Object.Module._extensions..js (module.js:579:10)
at Module.load (module.js:487:32)
at tryModuleLoad (module.js:446:12)
at Function.Module._load (module.js:438:3)
at Module.require (module.js:497:17)
at require (internal/module.js:20:19)

What's wrong?

**Comment by adamjohnsnow** [comment]
I also have this issue - any suggestion what went wrong?

**Comment by gibsongk** [comment]
I reverted to the Nov 3, 2017 version of the code, and it works. The Jan 31, 2018 version works, too.

**Comment by timtheguy** [comment]
I had the same issue, and using [the Jan 31, 2018 version](https://github.com/alexa/skill-sample-nodejs-decision-tree/blob/7787f678de01067f12927db99b84eab92b277f89/lambda/custom/index.js) worked immediately for me. Thanks @gibsongk! 

Not sure what would be necessary to correct the existing implementation.

**Comment by franklin-lobb** [comment]
The error being thrown does not occur in Node.js 8.10.  Is it correct that you used the ask-cli to create the Lambda function, and is it using Node.js 6.10?

The latest version of the ask-cli creates functions using Node.js 8.10.  As of today ```ask --version``` returns 1.3.1.  If you're on an earlier version, ask-cli may create the function using an earlier version of Node.js.  Run ```npm update -g ask-cli ``` to get the latest version of the ASK CLI.

If you update your ask-cli before deploying the first time, it will work correctly. 

If you want to fix a function you've already deployed, you have a couple of options.  Since the ask-cli does not modify the runtime for an existing function, you can fix an existing function by going into the Lambda console and changing the runtime to Node.js 8.10.  (Don't forget to click Save!)

Alternatively, you can remove the comma from this line: https://github.com/alexa/skill-sample-nodejs-decision-tree/blob/0c193888a0192bc6dd059e87df93443990718942/lambda/custom/index.js#L312

**Comment by timtheguy** [comment]
I was using the guide included in this repository to create and deploy the skill. I think [the included steps](https://github.com/alexa/skill-sample-nodejs-decision-tree/blob/master/instructions/2-lambda-function.md) direct the user to use Node.js 6.10 in AWS Lambda - or at the very least, it populated Node.js 6.10 automatically.

I haven't yet tried skill development with the ASK CLI, so maybe I'll give it a go there! Thanks for the reference.
